services:
    example-app:
        container_name: vite-plugin-envsubst-caddy-example
        image: vite-plugin-envsubst-caddy-example:latest
        build:
            context: ../..
            dockerfile: examples/caddy/Dockerfile
        ports:
            - 5173:80
        environment:
            - VITE_APP_TITLE=OVERRIDDEN_VARIABLE
