services:
    example-app:
        container_name: vite-plugin-envsubst-example
        image: vite-plugin-envsubst-example:latest
        build:
            context: .
            additional_contexts:
                repo: ../..
        ports:
            - 5173:80
        environment:
            - VITE_APP_TITLE=OVERRIDDEN_VARIABLE
